aliases:
  - &restore-dependencies-cache
    keys:
      - v1-dependencies-{{ checksum "package.json" }}

  - &save-dependencies-cache
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

defaults:
  - &job-defaults
      working_directory: ~/setsun.github.io
      docker:
        - image: circleci/node:8.9

version: 2
jobs:
  build:
    <<: *job-defaults
    steps:
      - checkout

      - attach_workspace:
          at: ~/setsun.github.io

      - restore_cache: *restore-dependencies-cache

      - run: npm install
      - run: npm run build

      - save_cache: *save-dependencies-cache

      - persist_to_workspace:
          root: .
          paths: .

  lint:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: ~/setsun.github.io

      - run: npm run lint

  flow:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: ~/setsun.github.io

      - run: npm run flow

  test:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: ~/setsun.github.io

      - run: npm run test

  deploy:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: ~/setsun.github.io

      - add_ssh_keys:
          fingerprints:
            - f8:eb:09:4e:ba:35:57:ad:cd:c1:ff:e1:07:2a:0a:b4

      # add github to known hosts
      - run: echo '16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48' >> ~/.ssh/known_hosts

      - deploy:
          name: GitHub Pages deploy
          command: ./bin/deploy-gh-pages.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - flow:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - flow
            - test
          filters:
            branches:
              only:
                - develop
