name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: | 
          yarn install
      - name: Deploy
        run: |
          yarn deploy